# Generated by Django 3.2.3 on 2021-08-17 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AdPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=255, null=True, verbose_name='Описание фото')),
                ('tg_file_id', models.CharField(max_length=255, verbose_name='ID файла в ТГ')),
                ('image', models.ImageField(upload_to='user_photos', verbose_name='Фотография')),
            ],
        ),
        migrations.CreateModel(
            name='PriceTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Наименование')),
                ('short_name', models.CharField(max_length=20, verbose_name='Краткое наименование')),
            ],
        ),
        migrations.CreateModel(
            name='RegisteredAd',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('album_start_id', models.PositiveIntegerField(null=True, verbose_name='Первое сообщение в альбоме')),
                ('album_end_id', models.PositiveIntegerField(null=True, verbose_name='Последнее сообщение в альбоме')),
                ('channel_message_id', models.PositiveIntegerField(db_index=True, null=True, verbose_name='Идентификатор сообщения в канале')),
                ('group_message_id', models.PositiveIntegerField(db_index=True, null=True, verbose_name='Идентификатор сообщения в группе')),
                ('feedback', models.TextField(max_length=4000, null=True, verbose_name='Отзыв пользователя')),
            ],
        ),
        migrations.CreateModel(
            name='SaleAd',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exact_price', models.CharField(max_length=30, null=True, verbose_name='Цена')),
                ('can_bargain', models.BooleanField(null=True, verbose_name='Торг возможен')),
                ('mileage', models.PositiveIntegerField(null=True, verbose_name='Пробег')),
                ('description', models.TextField(blank=True, max_length=4000, verbose_name='Подробное описание')),
                ('formed_at', models.DateTimeField(auto_now=True, db_index=True, verbose_name='Время составления')),
                ('location', models.CharField(blank=True, max_length=100, verbose_name='Местоположение для ремонта')),
                ('car_type', models.CharField(blank=True, max_length=50, verbose_name='Тип автомобиля')),
                ('is_complete', models.BooleanField(db_index=True, default=False, verbose_name='Флаг готовности заявки')),
                ('is_discarded', models.BooleanField(db_index=True, default=False, verbose_name='Флаг отказа от проведения заявки')),
                ('is_locked', models.BooleanField(db_index=True, default=False, verbose_name='Флаг завершения продажи')),
            ],
        ),
        migrations.CreateModel(
            name='SaleAdStage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default='', max_length=50, verbose_name='Наименование')),
                ('processor', models.CharField(max_length=50, null=True, verbose_name='Процессор обработки')),
                ('reply_pattern', models.TextField(null=True, verbose_name='Шаблон ответа')),
                ('buttons', models.JSONField(null=True, verbose_name='Набор кнопок')),
            ],
        ),
    ]
