# Generated by Django 3.2.3 on 2021-08-17 16:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bazaarapp', '0001_initial'),
        ('tgbot', '0001_initial'),
        ('convoapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='salead',
            name='dialog',
            field=models.OneToOneField(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bound_salead', to='convoapp.dialog'),
        ),
        migrations.AddField(
            model_name='salead',
            name='price_tag',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='bazaarapp.pricetag'),
        ),
        migrations.AddField(
            model_name='salead',
            name='stage',
            field=models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.SET_NULL, to='bazaarapp.saleadstage'),
        ),
        migrations.AddField(
            model_name='salead',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ads', to='tgbot.botuser'),
        ),
        migrations.AddField(
            model_name='registeredad',
            name='bound',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='registered', to='bazaarapp.salead'),
        ),
        migrations.AddField(
            model_name='adphoto',
            name='ad',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='bazaarapp.salead'),
        ),
    ]
