# Generated by Django 3.2.3 on 2021-08-18 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bazaarapp', '0002_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='salead',
            old_name='formed_at',
            new_name='created_at',
        ),
        migrations.AddField(
            model_name='registeredad',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True, null=True, verbose_name='Время создания'),
        ),
        migrations.AddField(
            model_name='registeredad',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, db_index=True, null=True, verbose_name='Время последней активности'),
        ),
        migrations.AddField(
            model_name='salead',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, db_index=True, verbose_name='Время последней активности'),
        ),
    ]
