# Generated by Django 3.2.3 on 2021-07-19 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bazaarapp', '0002_auto_20210719_2009'),
    ]

    operations = [
        migrations.AlterField(
            model_name='saleadstage',
            name='buttons',
            field=models.JSONField(null=True, verbose_name='Набор кнопок'),
        ),
        migrations.AlterField(
            model_name='saleadstage',
            name='reply_pattern',
            field=models.TextField(null=True, verbose_name='Шаблон ответа'),
        ),
    ]
