# Generated by Django 3.2.3 on 2021-08-18 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bazaarapp', '0003_auto_20210818_1527'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salead',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True, null=True, verbose_name='Время создания'),
        ),
        migrations.AlterField(
            model_name='salead',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, db_index=True, null=True, verbose_name='Время последней активности'),
        ),
        migrations.RunSQL("""
            UPDATE bazaarapp_registeredad AS bra
                SET created_at = (
                    SELECT created_at 
                        FROM bazaarapp_salead AS bsa
                        WHERE bsa.id = bra.bound_id
                );
            UPDATE bazaarapp_registeredad AS bra
                SET updated_at = (
                    SELECT created_at 
                        FROM bazaarapp_salead AS bsa
                        WHERE bsa.id = bra.bound_id
                );
            UPDATE bazaarapp_salead AS bsa
                SET updated_at = created_at;
        """, reverse_sql=""""""),
    ]
