# Generated by Django 3.2.3 on 2021-07-19 17:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bazaarapp', '0003_auto_20210719_2012'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=255, null=True, verbose_name='Описание фото')),
                ('tg_file_id', models.CharField(max_length=255, verbose_name='ID файла в ТГ')),
                ('image', models.ImageField(upload_to='user_photos', verbose_name='Фотография')),
                ('ad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='bazaarapp.salead')),
            ],
        ),
    ]
