# Generated by Django 3.2.3 on 2021-07-19 17:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bazaarapp', '0004_adphoto'),
    ]

    operations = [
        migrations.CreateModel(
            name='RegisteredAd',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('channel_message_id', models.PositiveIntegerField(db_index=True, null=True, verbose_name='Идентификатор сообщения в канале')),
                ('group_message_id', models.PositiveIntegerField(db_index=True, null=True, verbose_name='Идентификатор сообщения в группе')),
                ('feedback', models.TextField(max_length=4000, null=True, verbose_name='Отзыв пользователя')),
                ('bound', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='registered', to='bazaarapp.salead')),
            ],
        ),
    ]
