# Generated by Django 3.2.3 on 2021-07-20 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bazaarapp', '0005_registeredad'),
    ]

    operations = [
        migrations.AddField(
            model_name='registeredad',
            name='album_end_id',
            field=models.PositiveIntegerField(null=True, verbose_name='Последнее сообщение в альбоме'),
        ),
        migrations.AddField(
            model_name='registeredad',
            name='album_start_id',
            field=models.PositiveIntegerField(null=True, verbose_name='Первое сообщение в альбоме'),
        ),
    ]
