# Generated by Django 3.2.3 on 2021-09-06 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    replaces = [('bazaarapp', '0006_location_region'), ('bazaarapp', '0007_alter_salead_description'), ('bazaarapp', '0008_auto_20210906_1355')]

    dependencies = [
        ('bazaarapp', '0005_auto_20210818_1548'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salead',
            name='description',
            field=models.TextField(blank=True, max_length=750, verbose_name='Подробное описание'),
        ),
    ]
