# Generated by Django 3.2.3 on 2021-07-20 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bazaarapp', '0006_auto_20210720_2057'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salead',
            name='description',
            field=models.TextField(blank=True, max_length=4000, verbose_name='Подробное описание'),
        ),
    ]
