# Generated by Django 3.2.3 on 2021-08-21 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bazaarapp', '0006_location_region'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salead',
            name='description',
            field=models.TextField(blank=True, max_length=750, verbose_name='Подробное описание'),
        ),
    ]
