# Generated by Django 3.2.3 on 2021-09-06 10:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bazaarapp', '0007_alter_salead_description'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Location',
        ),
        migrations.DeleteModel(
            name='Region',
        ),
    ]
