# Generated by Django 3.2.3 on 2021-07-21 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bazaarapp', '0007_alter_salead_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='salead',
            name='is_locked',
            field=models.BooleanField(db_index=True, default=False, verbose_name='Флаг завершения продажи'),
        ),
    ]
