# Generated by Django 3.2.3 on 2021-07-23 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bazaarapp', '0008_salead_is_locked'),
    ]

    operations = [
        migrations.AddField(
            model_name='salead',
            name='can_bargain',
            field=models.BooleanField(null=True, verbose_name='Торг возможен'),
        ),
    ]
