# Generated by Django 3.2.3 on 2021-09-16 16:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bazaarapp', '0009_registeredad_is_deleted'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registeredad',
            name='bound',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registered_posts', to='bazaarapp.salead'),
        ),
    ]
