# Generated by Django 3.2.3 on 2021-09-23 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bazaarapp', '0010_alter_registeredad_bound'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salead',
            name='exact_price',
            field=models.PositiveIntegerField(null=True, verbose_name='Цена'),
        ),
    ]
