# Generated by Django 3.2.3 on 2021-10-11 18:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tgbot', '0009_auto_20211011_2015'),
        ('bazaarapp', '0011_alter_salead_exact_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salead',
            name='location_desc',
            field=models.CharField(blank=True, max_length=100, verbose_name='Описание местоположения'),
        ),
        migrations.AlterField(
            model_name='salead',
            name='location_key',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='tgbot.location'),
        ),
    ]
