# Generated by Django 3.2.3 on 2021-09-24 18:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('filterapp', '0001_initial_squashed_0002_auto_20210923_1925'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bazaarfilter',
            name='price_ranges',
        ),
    ]
