# Generated by Django 3.2.3 on 2021-11-09 16:56
from functools import partial

from django.db import migrations

from utils.migrate import add_stages, del_stages


class Migration(migrations.Migration):

    dependencies = [
        ('filterapp', '0002_auto_20211029_1753'),
    ]

    operations = [
        migrations.RunPython(
            partial(
                add_stages,
                model_name="filterapp.RepairsFilter",
                stage_model_name="filterapp.RepairsFilterStage",
                stages=[
                    dict(id=5, name="ASK_PAYMENT", processor="ConfirmPaymentProcessor"),
                    dict(id=6, name="INVOICE_REQUESTED", processor="ProcessPaymentProcessor"),
                ]
            ),
            reverse_code=partial(
                del_stages,
                model_name="filterapp.RepairsFilter",
                stage_model_name="filterapp.RepairsFilterStage",
                ids=[5, 6],
            )
        )
    ]
