# Generated by Django 3.2.3 on 2022-02-13 10:56
from functools import partial

from django.db import migrations

from utils.migrate import add_stages, del_stages


class Migration(migrations.Migration):

    dependencies = [
        ('filterapp', '0003_auto_20211109_1956'),
    ]

    operations = [
        migrations.RunPython(
            partial(
                add_stages,
                model_name="filterapp.RepairsFilter",
                stage_model_name="filterapp.RepairsFilterStage",
                stages=[
                    dict(id=3, name="GET_COMPANY_NAME", processor="CompanyNameInputProcessor"),
                ]
            ),
            reverse_code=partial(
                del_stages,
                model_name="filterapp.RepairsFilter",
                stage_model_name="filterapp.RepairsFilterStage",
                ids=[3],
            )
        )
    ]
