# Generated by Django 3.2.3 on 2022-02-20 02:35
from functools import partial

from django.db import migrations

from utils.migrate import del_stages, add_stages


class Migration(migrations.Migration):

    dependencies = [
        ('filterapp', '0004_auto_20220213_1356'),
    ]

    operations = [
        migrations.RunPython(
            partial(
                add_stages,
                model_name="filterapp.BazaarFilter",
                stage_model_name="filterapp.BazaarFilterStage",
                stages=[
                    dict(id=6, name="ASK_PAYMENT", processor="ConfirmPaymentProcessor"),
                    dict(id=7, name="INVOICE_REQUESTED", processor="ProcessPaymentProcessor"),
                ]
            ),
            reverse_code=partial(
                del_stages,
                model_name="filterapp.BazaarFilter",
                stage_model_name="filterapp.BazaarFilterStage",
                ids=[6, 7],
            )
        )
    ]
