# Generated by Django 3.2.3 on 2021-11-09 16:55

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tgbot', '0010_rename_tag_repairstype'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Время создания')),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True, verbose_name='Время последней активности')),
                ('tier', models.PositiveSmallIntegerField(choices=[(1, 'Месячная'), (2, 'Годовая'), (3, 'Навсегда')], verbose_name='Уровень подписки')),
                ('service', models.PositiveSmallIntegerField(choices=[(1, 'Бот фильтров автосервиса'), (2, 'Бот фильтров автобазара')], verbose_name='Сервис, на который оформлена подписка')),
                ('expiry_time', models.DateTimeField(db_index=True, default=django.utils.timezone.now, verbose_name='Время окончания подписки')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='subscriptions', to='tgbot.botuser', verbose_name='Пользователь')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
