# Generated by Django 3.2.3 on 2022-02-08 16:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('paymentapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='dialog',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='order', to='convoapp.dialog', verbose_name='Разговор'),
        ),
    ]
