# Generated by Django 3.2.3 on 2021-05-22 10:22

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BotUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, verbose_name='Полное имя для бота')),
                ('first_name', models.CharField(blank=True, max_length=100, verbose_name='Полное имя в ТГ')),
                ('last_name', models.CharField(blank=True, max_length=100, verbose_name='Полное имя в ТГ')),
                ('user_id', models.PositiveIntegerField(unique=True, verbose_name='ID в ТГ')),
                ('username', models.CharField(max_length=100, null=True, verbose_name='Ник в ТГ')),
                ('location', models.CharField(max_length=200, null=True, verbose_name='Указанное местоположение')),
                ('dialog_stage', models.PositiveSmallIntegerField(choices=[(1, 'Стадия 1. Приветствие')], default=1, verbose_name='Состояние диалога')),
                ('last_active', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Время последней активности')),
            ],
        ),
    ]
