# Generated by Django 3.2.3 on 2021-08-18 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tgbot', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='botuser',
            old_name='last_active',
            new_name='updated_at',
        ),
        migrations.AddField(
            model_name='registeredrequest',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True, null=True, verbose_name='Время создания'),
        ),
        migrations.AddField(
            model_name='registeredrequest',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, db_index=True, null=True, verbose_name='Время последней активности'),
        ),
        migrations.AddField(
            model_name='workrequest',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, db_index=True, verbose_name='Время последней активности'),
        ),
        migrations.AlterField(
            model_name='workrequest',
            name='formed_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Время составления'),
        ),
    ]
