# Generated by Django 3.2.3 on 2021-05-22 14:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tgbot', '0002_auto_20210522_1711'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Request',
            new_name='WorkRequest',
        ),
    ]
