# Generated by Django 3.2.3 on 2021-08-18 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tgbot', '0002_auto_20210818_1436'),
    ]

    operations = [
        migrations.RunSQL("""
            UPDATE tgbot_registeredrequest AS trr
                SET created_at = (
                    SELECT formed_at 
                        FROM tgbot_workrequest AS tw
                        WHERE tw.id = trr.bound_id
                );
            UPDATE tgbot_registeredrequest AS trr
                SET updated_at = (
                    SELECT formed_at 
                        FROM tgbot_workrequest AS tw
                        WHERE tw.id = trr.bound_id
                );
            UPDATE tgbot_workrequest AS tw
                SET updated_at = formed_at;
        """, reverse_sql=""""""),
        migrations.RenameField(
            model_name='workrequest',
            old_name='formed_at',
            new_name='created_at',
        ),
        migrations.AlterField(
            model_name='botuser',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True, null=True, verbose_name='Время создания'),
        ),
        migrations.AlterField(
            model_name='botuser',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, db_index=True, null=True, verbose_name='Время последней активности'),
        ),
    ]
