# Generated by Django 3.2.3 on 2021-05-22 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tgbot', '0003_rename_request_workrequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='requestphoto',
            name='tg_file_id',
            field=models.CharField(default=0, max_length=100, verbose_name='ID файла в ТГ'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='workrequest',
            name='is_complete',
            field=models.BooleanField(default=False, verbose_name='Флаг готовности заявки'),
        ),
        migrations.AlterField(
            model_name='botuser',
            name='dialog_stage',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Стадия 1. Приветствие'), (2, 'Стадия 2. Подтвердить создание заявки'), (3, 'Стадия 3. Получить имя'), (4, 'Стадия 4. Получить название заявки'), (5, 'Стадия 5. Получить описание заявки'), (6, 'Стадия 6. Предложить отправить фотографии'), (7, 'Стадия 7. Получить фотографии'), (8, 'Стадия 8. Получить местоположение'), (9, 'Стадия 9. Получить телефон'), (10, 'Стадия 10. Проверить заявку')], default=1, verbose_name='Состояние диалога'),
        ),
        migrations.AlterField(
            model_name='requestphoto',
            name='image',
            field=models.ImageField(upload_to='user_photos', verbose_name='Фотография'),
        ),
    ]
