# Generated by Django 3.2.3 on 2021-05-22 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tgbot', '0004_auto_20210522_1852'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requestphoto',
            name='description',
            field=models.CharField(max_length=255, null=True, verbose_name='Описание фото'),
        ),
    ]
