# Generated by Django 3.2.3 on 2021-09-06 10:55

from django.db import migrations, models
import django.db.models.deletion

from garage_band_bot.settings import BASE_DIR


SQL_FILE = f"{BASE_DIR}\\tgbot\\sql\\locations.sql"


def load_sql(filename):
    with open(filename, 'r') as f:
        return f.read()


class Migration(migrations.Migration):

    dependencies = [
        ('tgbot', '0005_alter_messengerbot_telegram_instance'),
    ]

    operations = [
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=20, unique=True, verbose_name='Наименование')),
            ],
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=50, verbose_name='Наименование')),
                ('region', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='locations', to='tgbot.region')),
            ],
        ),
        migrations.RunSQL(load_sql(SQL_FILE), reverse_sql=""),
    ]
