# Generated by Django 3.2.3 on 2021-05-25 13:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tgbot', '0005_alter_requestphoto_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='botuser',
            name='dialog_stage',
        ),
        migrations.AlterField(
            model_name='workrequest',
            name='title',
            field=models.CharField(blank=True, max_length=255, verbose_name='Наименование задачи'),
        ),
        migrations.CreateModel(
            name='Dialog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stage', models.PositiveSmallIntegerField(choices=[(1, 'Стадия 1. Приветствие'), (2, 'Стадия 2. Подтвердить создание заявки'), (3, 'Стадия 3. Получить имя'), (4, 'Стадия 4. Получить название заявки'), (5, 'Стадия 5. Получить описание заявки'), (6, 'Стадия 6. Предложить отправить фотографии'), (7, 'Стадия 7. Получить фотографии'), (8, 'Стадия 8. Получить местоположение'), (9, 'Стадия 9. Получить телефон'), (10, 'Стадия 10. Проверить заявку'), (11, 'Стадия 11. Работа завершена')], default=1, verbose_name='Состояние диалога')),
                ('request', models.OneToOneField(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dialog', to='tgbot.workrequest')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='dialog', to='tgbot.botuser')),
            ],
        ),
    ]
