# Generated by Django 3.2.3 on 2021-09-16 19:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tgbot', '0006_location_region'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registeredrequest',
            name='bound',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='registered_posts', to='tgbot.workrequest'),
        ),
        migrations.AddField(
            model_name='registeredrequest',
            name='is_deleted',
            field=models.BooleanField(db_index=True, default=False, verbose_name='Сообщение удалено из канала'),
        ),
    ]
