# Generated by Django 3.2.3 on 2021-05-26 22:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tgbot', '0006_auto_20210525_1656'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dialog',
            name='request',
        ),
        migrations.AddField(
            model_name='workrequest',
            name='dialog',
            field=models.OneToOneField(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='request', to='tgbot.dialog'),
        ),
    ]
