# Generated by Django 3.2.3 on 2021-10-11 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tgbot', '0007_alter_registeredrequest_bound'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workrequeststage',
            name='buttons',
            field=models.JSONField(null=True, verbose_name='Набор кнопок'),
        ),
        migrations.AlterField(
            model_name='workrequeststage',
            name='reply_pattern',
            field=models.TextField(null=True, verbose_name='Шаблон ответа'),
        ),
        migrations.RenameField(
            model_name='workrequest',
            old_name='location',
            new_name='location_desc',
        ),
        migrations.AlterField(
            model_name='workrequest',
            name='location_desc',
            field=models.CharField(blank=True, max_length=100, verbose_name='Описание местоположения'),
        ),
        migrations.AddField(
            model_name='workrequest',
            name='location_key',
            field=models.ForeignKey(null=True, on_delete=models.deletion.SET_NULL, to='tgbot.location'),
        ),
    ]
