# Generated by Django 3.2.3 on 2021-05-29 17:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tgbot', '0008_auto_20210528_2130'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workrequest',
            name='dialog',
            field=models.OneToOneField(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='request', to='tgbot.dialog'),
        ),
    ]
