# Generated by Django 3.2.3 on 2022-02-01 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tgbot', '0010_rename_tag_repairstype'),
    ]

    operations = [
        migrations.AlterField(
            model_name='botuser',
            name='user_id',
            field=models.PositiveBigIntegerField(db_index=True, unique=True, verbose_name='ID в ТГ'),
        ),
    ]
