# Generated by Django 3.2.3 on 2021-06-01 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tgbot', '0010_auto_20210601_2158'),
    ]

    operations = [
        migrations.AlterField(
            model_name='botuser',
            name='name',
            field=models.CharField(blank=True, max_length=50, verbose_name='Полное имя пользователя'),
        ),
        migrations.AlterField(
            model_name='workrequest',
            name='title',
            field=models.CharField(blank=True, max_length=70, verbose_name='Наименование задачи'),
        ),
    ]
