# Generated by Django 3.2.3 on 2021-06-02 15:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tgbot', '0011_auto_20210601_2341'),
    ]

    operations = [
        migrations.CreateModel(
            name='RegisteredRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message_id', models.PositiveIntegerField(null=True, verbose_name='Идентификатор сообщения в канале')),
                ('request', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='registered', to='tgbot.workrequest')),
            ],
        ),
    ]
