# Generated by Django 3.2.3 on 2021-06-02 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tgbot', '0012_registeredrequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='botuser',
            name='is_banned',
            field=models.BooleanField(db_index=True, default=False, verbose_name='В бане'),
        ),
        migrations.AlterField(
            model_name='botuser',
            name='user_id',
            field=models.PositiveIntegerField(db_index=True, unique=True, verbose_name='ID в ТГ'),
        ),
        migrations.AlterField(
            model_name='registeredrequest',
            name='message_id',
            field=models.PositiveIntegerField(db_index=True, null=True, verbose_name='Идентификатор сообщения в канале'),
        ),
        migrations.AlterField(
            model_name='workrequest',
            name='formed_at',
            field=models.DateTimeField(auto_now=True, db_index=True, verbose_name='Время составления'),
        ),
        migrations.AlterField(
            model_name='workrequest',
            name='is_complete',
            field=models.BooleanField(db_index=True, default=False, verbose_name='Флаг готовности заявки'),
        ),
    ]
