# Generated by Django 3.2.3 on 2022-04-02 12:00
from functools import partial

from django.db import migrations

from utils.migrate import add_foreign_keys, del_foreign_keys

NEW_TAG_ROWS = [
    dict(id=7, name="Запчасти"),
    dict(id=8, name="Топливо"),
]


class Migration(migrations.Migration):

    dependencies = [
        ('tgbot', '0012_botuser_company_name'),
    ]

    operations = [
        migrations.RunPython(
            code=partial(
                add_foreign_keys,
                model_name='tgbot.WorkRequest',
                key_model_name='tgbot.RepairsType',
                keys=NEW_TAG_ROWS,
                relation_name="tag",
            ),
            reverse_code=partial(
                del_foreign_keys,
                model_name='tgbot.WorkRequest',
                key_model_name='tgbot.RepairsType',
                ids=[7, 8],
                relation_name="tag",
            ),
        )
    ]
