# Generated by Django 3.2.3 on 2021-06-02 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tgbot', '0013_auto_20210602_2341'),
    ]

    operations = [
        migrations.AddField(
            model_name='botuser',
            name='is_staff',
            field=models.BooleanField(db_index=True, default=False, verbose_name='Админ'),
        ),
    ]
