# Generated by Django 3.2.3 on 2021-06-03 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tgbot', '0014_botuser_is_staff'),
    ]

    operations = [
        migrations.AlterField(
            model_name='botuser',
            name='first_name',
            field=models.CharField(blank=True, max_length=100, verbose_name='Имя в ТГ'),
        ),
        migrations.AlterField(
            model_name='botuser',
            name='last_name',
            field=models.CharField(blank=True, max_length=100, verbose_name='Фамилия в ТГ'),
        ),
        migrations.AlterField(
            model_name='botuser',
            name='location',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Указанное местоположение'),
        ),
    ]
