# Generated by Django 3.2.3 on 2021-06-08 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tgbot', '0015_auto_20210603_2031'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workrequest',
            name='phone',
        ),
        migrations.AddField(
            model_name='botuser',
            name='phone',
            field=models.CharField(blank=True, max_length=20, verbose_name='Номер телефона'),
        ),
    ]
