# Generated by Django 3.2.3 on 2021-06-08 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tgbot', '0016_auto_20210608_1556'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requestphoto',
            name='tg_file_id',
            field=models.CharField(max_length=255, verbose_name='ID файла в ТГ'),
        ),
    ]
