# Generated by Django 3.2.3 on 2021-06-10 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tgbot', '0019_alter_dialog_stage'),
    ]

    operations = [
        migrations.AddField(
            model_name='dialog',
            name='is_finished',
            field=models.BooleanField(db_index=True, default=False, verbose_name='Диалог завершён'),
        ),
    ]
