# Generated by Django 3.2.3 on 2021-06-10 16:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tgbot', '0020_dialog_is_finished'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dialog',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dialog', to='tgbot.botuser'),
        ),
    ]
