# Generated by Django 3.2.3 on 2021-06-10 17:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tgbot', '0021_alter_dialog_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name='Текст сообщения')),
                ('stage', models.PositiveSmallIntegerField(choices=[(1, 'Приветствие'), (2, 'Получить имя'), (3, 'Получить категорию заявки'), (4, 'Получить описание заявки'), (5, 'Предложить отправить фотографии'), (6, 'Получить местоположение'), (7, 'Получить телефон'), (8, 'Проверить заявку'), (9, 'Работа завершена')], verbose_name='Стадия диалога')),
                ('is_incoming', models.BooleanField(db_index=True, default=True, verbose_name='Входящее')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Время создания')),
                ('dialog', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='tgbot.dialog')),
            ],
        ),
    ]
