# Generated by Django 3.2.3 on 2021-06-10 21:23

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('tgbot', '0022_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='dialog',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Время создания'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='dialog',
            name='last_active',
            field=models.DateTimeField(auto_now=True, verbose_name='Время последней активности'),
        ),
    ]
