# Generated by Django 3.2.3 on 2021-06-11 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tgbot', '0023_auto_20210611_0023'),
    ]

    operations = [
        migrations.AddField(
            model_name='workrequest',
            name='is_discarded',
            field=models.BooleanField(db_index=True, default=False, verbose_name='Флаг отказа от проведения заявки'),
        ),
    ]
