# Generated by Django 3.2.3 on 2021-06-15 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tgbot', '0024_workrequest_is_discarded'),
    ]

    operations = [
        migrations.AddField(
            model_name='workrequest',
            name='car_type',
            field=models.CharField(blank=True, max_length=50, verbose_name='Тип автомобиля'),
        ),
        migrations.AlterField(
            model_name='dialog',
            name='stage',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Приветствие'), (2, 'Получить имя'), (3, 'Получить категорию заявки'), (4, 'Получить тип автомобиля'), (5, 'Получить описание заявки'), (6, 'Предложить отправить фотографии'), (7, 'Проверить заявку'), (8, 'Работа завершена')], default=1, verbose_name='Состояние диалога'),
        ),
        migrations.AlterField(
            model_name='message',
            name='stage',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Приветствие'), (2, 'Получить имя'), (3, 'Получить категорию заявки'), (4, 'Получить тип автомобиля'), (5, 'Получить описание заявки'), (6, 'Предложить отправить фотографии'), (7, 'Проверить заявку'), (8, 'Работа завершена')], verbose_name='Стадия диалога'),
        ),
    ]
