# Generated by Django 3.2.3 on 2021-06-17 15:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tgbot', '0025_auto_20210615_1200'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workrequest',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requests', to='tgbot.botuser'),
        ),
    ]
