# Generated by Django 3.2.3 on 2021-06-28 16:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('convoapp', '0001_initial'),
        ('tgbot', '0026_alter_workrequest_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dialog',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='tgbot.botuser'),
        ),
        migrations.AlterField(
            model_name='workrequest',
            name='dialog',
            field=models.OneToOneField(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='request', to='convoapp.dialog'),
        ),
    ]
