# Generated by Django 3.2.3 on 2021-06-30 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tgbot', '0028_auto_20210628_1945'),
    ]

    operations = [
        migrations.AddField(
            model_name='registeredrequest',
            name='feedback',
            field=models.TextField(max_length=4000, null=True, verbose_name='Отзыв пользователя'),
        ),
    ]
