# Generated by Django 3.2.3 on 2021-07-09 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tgbot', '0029_registeredrequest_feedback'),
    ]

    operations = [
        migrations.RenameField(
            model_name='registeredrequest',
            old_name='message_id',
            new_name='channel_message_id',
        ),
        migrations.AddField(
            model_name='registeredrequest',
            name='group_message_id',
            field=models.PositiveIntegerField(db_index=True, null=True, verbose_name='Идентификатор сообщения в группе'),
        ),
    ]
