# Generated by Django 3.2.3 on 2021-07-15 16:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tgbot', '0030_auto_20210709_2104'),
    ]

    operations = [
        migrations.CreateModel(
            name='TGInstance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(max_length=50, verbose_name='Токен ТГ')),
                ('publish_id', models.IntegerField(verbose_name='Основной канал бота')),
                ('publish_name', models.CharField(max_length=100, verbose_name='Название канала')),
                ('admin_group_id', models.IntegerField(null=True, verbose_name='Группа администрирования')),
                ('discussion_group_id', models.IntegerField(null=True, verbose_name='Группа обсуждения')),
                ('feedback_group_id', models.IntegerField(null=True, verbose_name='Группа фидбека')),
            ],
        ),
        migrations.CreateModel(
            name='MessengerBot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Наименование')),
                ('bound_object', models.CharField(max_length=50, verbose_name='Рабочий объект')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='Бот включён')),
                ('is_debug', models.BooleanField(db_index=True, default=True, verbose_name="Для дебага")),
                ('telegram_instance', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bot', to='tgbot.tginstance')),
                ('bound_app', models.CharField(default='tgbot', max_length=50, verbose_name='Приложение для обработки объекта')),
            ],
        ),
    ]
