# Generated by Django 3.2.3 on 2021-07-15 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tgbot', '0031_messengerbot_tginstance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tginstance',
            name='admin_group_id',
            field=models.BigIntegerField(null=True, verbose_name='Группа администрирования'),
        ),
        migrations.AlterField(
            model_name='tginstance',
            name='discussion_group_id',
            field=models.BigIntegerField(null=True, verbose_name='Группа обсуждения'),
        ),
        migrations.AlterField(
            model_name='tginstance',
            name='feedback_group_id',
            field=models.BigIntegerField(null=True, verbose_name='Группа фидбека'),
        ),
        migrations.AlterField(
            model_name='tginstance',
            name='publish_id',
            field=models.BigIntegerField(verbose_name='Основной канал бота'),
        ),
        migrations.RunSQL("""
            INSERT INTO tgbot_tginstance (
                id,
                token,
                publish_id,
                publish_name,
                admin_group_id,
                discussion_group_id,
                feedback_group_id
            ) VALUES (
                1,
                'n/a',
                1,
                'GarageBandTest',
                1,
                1,
                1
            );
            INSERT INTO tgbot_messengerbot (
                id,
                name,
                bound_object,
                is_active,
                is_debug,
                telegram_instance_id,
                bound_app
            ) VALUES (
                1,
                'бот ремонт',
                'WorkRequest',
                TRUE,
                TRUE,
                1,
                'tgbot'
            );
        """, reverse_sql=""),
    ]
