# Generated by Django 3.2.3 on 2021-07-16 11:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('convoapp', '0005_dialog_bot'),
        ('tgbot', '0032_auto_20210715_1938'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workrequest',
            name='dialog',
            field=models.OneToOneField(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bound', to='convoapp.dialog'),
        ),
    ]
