# Generated by Django 3.2.3 on 2021-07-19 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tgbot', '0036_move_stage_info_20210717_1836'),
    ]

    operations = [
        migrations.AddField(
            model_name='messengerbot',
            name='bound_app',
            field=models.CharField(default='tgbot', max_length=50, verbose_name='Приложение для обработки объекта'),
        ),
    ]
