# Generated by Django 3.2.3 on 2021-07-19 17:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('convoapp', '0007_alter_message_stage'),
        ('tgbot', '0038_alter_workrequest_dialog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workrequest',
            name='dialog',
            field=models.OneToOneField(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bound_workrequest', to='convoapp.dialog'),
        ),
    ]
