# Generated by Django 3.2.3 on 2021-07-19 17:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tgbot', '0039_alter_workrequest_dialog'),
    ]

    operations = [
        migrations.RenameField(
            model_name='registeredrequest',
            old_name='request',
            new_name='bound',
        ),
    ]
