# Generated by Django 3.2.3 on 2021-07-19 20:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tgbot', '0040_rename_request_registeredrequest_bound'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workrequest',
            name='stage',
            field=models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.SET_NULL, to='tgbot.workrequeststage'),
        ),
    ]
