# Generated by Django 3.2.3 on 2021-07-21 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tgbot', '0041_alter_workrequest_stage'),
    ]

    operations = [
        migrations.AddField(
            model_name='workrequest',
            name='is_locked',
            field=models.BooleanField(db_index=True, default=False, verbose_name='Флаг полного завершения работы по заявке'),
        ),
    ]
