# Generated by Django 3.2.3 on 2022-02-08 13:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True
    # replaces = [('subscribeapp', '0001_initial'), ('subscribeapp', '0002_auto_20220207_0001')]

    dependencies = [
        ('tgbot', '0011_alter_botuser_user_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Время создания')),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True, verbose_name='Время последней активности')),
                ('tier', models.PositiveSmallIntegerField(choices=[(1, 'Месячная'), (2, 'Годовая'), (3, 'Навсегда')], verbose_name='Уровень подписки')),
                ('service', models.PositiveSmallIntegerField(choices=[(1, 'Бот фильтров автосервиса'), (2, 'Бот фильтров автобазара')], verbose_name='Сервис, на который оформлена подписка')),
                ('expiry_time', models.DateTimeField(db_index=True, null=True, verbose_name='Время окончания подписки')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='subscriptions', to='tgbot.botuser', verbose_name='Пользователь')),
                ('is_active', models.BooleanField(db_index=True, default=False, verbose_name='Подписка активна')),
                ('start_time', models.DateTimeField(db_index=True, null=True, verbose_name='Время начала подписки')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
