# Generated by Django 3.2.3 on 2021-06-28 16:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tgbot', '0026_alter_workrequest_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dialog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stage', models.PositiveSmallIntegerField(choices=[(1, 'Приветствие'), (2, 'Получить имя'), (3, 'Получить категорию заявки'), (4, 'Получить тип автомобиля'), (5, 'Получить описание заявки'), (6, 'Предложить отправить фотографии'), (7, 'Проверить заявку'), (8, 'Работа завершена')], default=1, verbose_name='Состояние диалога')),
                ('is_finished', models.BooleanField(db_index=True, default=False, verbose_name='Диалог завершён')),
                ('last_active', models.DateTimeField(auto_now=True, verbose_name='Время последней активности')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Время создания')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dialog', to='tgbot.botuser')),
            ],
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name='Текст сообщения')),
                ('stage', models.PositiveSmallIntegerField(choices=[(1, 'Приветствие'), (2, 'Получить имя'), (3, 'Получить категорию заявки'), (4, 'Получить тип автомобиля'), (5, 'Получить описание заявки'), (6, 'Предложить отправить фотографии'), (7, 'Проверить заявку'), (8, 'Работа завершена')], verbose_name='Стадия диалога')),
                ('is_incoming', models.BooleanField(db_index=True, default=True, verbose_name='Входящее')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Время создания')),
                ('dialog', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='convoapp.dialog')),
            ],
        ),
    ]
