# Generated by Django 3.2.3 on 2021-08-17 16:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dialog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_finished', models.BooleanField(db_index=True, default=False, verbose_name='Диалог завершён')),
                ('last_active', models.DateTimeField(auto_now=True, verbose_name='Время последней активности')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Время создания')),
            ],
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name='Текст сообщения')),
                ('stage', models.PositiveSmallIntegerField(verbose_name='Стадия диалога')),
                ('message_id', models.IntegerField(default=None, null=True, verbose_name='Номер сообщения')),
                ('is_incoming', models.BooleanField(db_index=True, default=True, verbose_name='Входящее')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Время создания')),
                ('dialog', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='convoapp.dialog')),
            ],
        ),
    ]
