# Generated by Django 3.2.3 on 2021-06-28 16:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('convoapp', '0001_initial'),
    ]

    operations = [
        migrations.RunSQL("""
            INSERT INTO convoapp_dialog (
                id,
                user_id,
                stage,
                is_finished,
                last_active,
                created_at
            )
            SELECT 
                id,
                user_id,
                stage,
                is_finished,
                last_active,
                created_at
            FROM
                tgbot_dialog;
            INSERT INTO convoapp_message (
                id,
                dialog_id,
                text,
                stage,
                is_incoming,
                created_at
            )
            SELECT 
                id,
                dialog_id,
                text,
                stage,
                is_incoming,
                created_at
            FROM
                tgbot_message;
            SELECT 
                setval(pg_get_serial_sequence('"convoapp_dialog"','id'),
                coalesce(max("id"), 1), max("id") IS NOT null)
            FROM
                "convoapp_dialog";
            SELECT
                setval(pg_get_serial_sequence('"convoapp_message"','id'),
                coalesce(max("id"), 1), max("id") IS NOT null)
            FROM
                "convoapp_message";

        """, reverse_sql="""
            INSERT INTO tgbot_dialog (
                id,
                user_id,
                stage,
                is_finished,
                last_active,
                created_at
            )
            SELECT 
                id,
                user_id,
                stage,
                is_finished,
                last_active,
                created_at
            FROM
                convoapp_dialog;
            INSERT INTO tgbot_message (
                id,
                dialog_id,
                text,
                stage,
                is_incoming,
                created_at
            )
            SELECT 
                id,
                dialog_id,
                text,
                stage,
                is_incoming,
                created_at
            FROM
                convoapp_message;
        """)
    ]
