# Generated by Django 3.2.3 on 2021-08-17 16:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tgbot', '0001_initial'),
        ('convoapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dialog',
            name='bot',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='dialog', to='tgbot.messengerbot'),
        ),
        migrations.AddField(
            model_name='dialog',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dialog', to='tgbot.botuser'),
        ),
    ]
