# Generated by Django 3.2.3 on 2021-06-30 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('convoapp', '0002_auto_20210628_1932'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='message_id',
            field=models.IntegerField(default=None, null=True, verbose_name='Номер сообщения'),
        ),
        migrations.AlterField(
            model_name='dialog',
            name='stage',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Приветствие'), (2, 'Получить имя'), (3, 'Получить категорию заявки'), (4, 'Получить тип автомобиля'), (5, 'Получить описание заявки'), (6, 'Предложить отправить фотографии'), (7, 'Проверить заявку'), (8, 'Работа завершена'), (9, 'Оставить отзыв')], default=1, verbose_name='Состояние диалога'),
        ),
        migrations.AlterField(
            model_name='message',
            name='stage',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Приветствие'), (2, 'Получить имя'), (3, 'Получить категорию заявки'), (4, 'Получить тип автомобиля'), (5, 'Получить описание заявки'), (6, 'Предложить отправить фотографии'), (7, 'Проверить заявку'), (8, 'Работа завершена'), (9, 'Оставить отзыв')], verbose_name='Стадия диалога'),
        ),
    ]
