# Generated by Django 3.2.3 on 2021-08-18 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('convoapp', '0002_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dialog',
            old_name='last_active',
            new_name='updated_at',
        ),
        migrations.AddField(
            model_name='message',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, db_index=True, null=True, verbose_name='Время последней активности'),
        ),
        migrations.AlterField(
            model_name='message',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True, null=True, verbose_name='Время создания'),
        ),
        migrations.RunSQL("""
            UPDATE convoapp_message AS cm
                SET updated_at = created_at;
        """, reverse_sql=""""""),
    ]
