# Generated by Django 3.2.3 on 2021-08-18 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('convoapp', '0003_auto_20210818_1520'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dialog',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True, null=True, verbose_name='Время создания'),
        ),
        migrations.AlterField(
            model_name='dialog',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, db_index=True, null=True, verbose_name='Время последней активности'),
        ),
    ]
