# Generated by Django 3.2.3 on 2021-07-09 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('convoapp', '0003_auto_20210630_1945'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dialog',
            name='stage',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Приветствие'), (2, 'Получить имя'), (3, 'Получить категорию заявки'), (4, 'Получить тип автомобиля'), (5, 'Получить описание заявки'), (6, 'Предложить отправить фотографии'), (7, 'Проверить заявку'), (8, 'Работа завершена'), (9, 'Оставить отзыв'), (10, 'Отзыв получен')], default=1, verbose_name='Состояние диалога'),
        ),
        migrations.AlterField(
            model_name='message',
            name='stage',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Приветствие'), (2, 'Получить имя'), (3, 'Получить категорию заявки'), (4, 'Получить тип автомобиля'), (5, 'Получить описание заявки'), (6, 'Предложить отправить фотографии'), (7, 'Проверить заявку'), (8, 'Работа завершена'), (9, 'Оставить отзыв'), (10, 'Отзыв получен')], verbose_name='Стадия диалога'),
        ),
    ]
