# Generated by Django 3.2.3 on 2021-07-16 11:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tgbot', '0032_auto_20210715_1938'),
        ('convoapp', '0004_auto_20210709_2104'),
    ]

    operations = [
        migrations.AddField(
            model_name='dialog',
            name='bot',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='dialog', to='tgbot.messengerbot'),
        ),
    ]
