# Generated by Django 3.2.3 on 2021-07-18 12:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('convoapp', '0005_dialog_bot'),
        ('tgbot', '0036_move_stage_info_20210717_1836'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dialog',
            name='stage',
        ),
    ]
