# Generated by Django 3.2.3 on 2021-09-14 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('convoapp', '0005_auto_20210818_1548'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='stage',
            field=models.PositiveSmallIntegerField(null=True, verbose_name='Стадия диалога'),
        ),
    ]
