# Generated by Django 3.2.3 on 2021-07-19 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('convoapp', '0006_remove_dialog_stage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='stage',
            field=models.PositiveSmallIntegerField(verbose_name='Стадия диалога'),
        ),
    ]
